// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_trail.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAuditTrail = `-- name: CreateAuditTrail :execresult
INSERT INTO audit_trail (table_name, row_id, action, changes, actor_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateAuditTrailParams struct {
	TableName string         `json:"table_name"`
	RowID     int32          `json:"row_id"`
	Action    string         `json:"action"`
	Changes   sql.NullString `json:"changes"`
	ActorID   sql.NullInt32  `json:"actor_id"`
}

func (q *Queries) CreateAuditTrail(ctx context.Context, arg CreateAuditTrailParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAuditTrail,
		arg.TableName,
		arg.RowID,
		arg.Action,
		arg.Changes,
		arg.ActorID,
	)
}

const getAuditTrail = `-- name: GetAuditTrail :one
SELECT id, table_name, row_id, action, changes, actor_id, created_at FROM audit_trail WHERE id = ? LIMIT 1
`

func (q *Queries) GetAuditTrail(ctx context.Context, id int32) (AuditTrail, error) {
	row := q.db.QueryRowContext(ctx, getAuditTrail, id)
	var i AuditTrail
	err := row.Scan(
		&i.ID,
		&i.TableName,
		&i.RowID,
		&i.Action,
		&i.Changes,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditTrails = `-- name: ListAuditTrails :many
SELECT id, table_name, row_id, action, changes, actor_id, created_at FROM audit_trail ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListAuditTrailsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditTrails(ctx context.Context, arg ListAuditTrailsParams) ([]AuditTrail, error) {
	rows, err := q.db.QueryContext(ctx, listAuditTrails, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditTrail
	for rows.Next() {
		var i AuditTrail
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.RowID,
			&i.Action,
			&i.Changes,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
