// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_token.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_token WHERE token = ?
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceToken, token)
	return err
}

const listActivePatientTokens = `-- name: ListActivePatientTokens :many
SELECT dt.token
FROM device_token dt
JOIN ` + "`" + `user` + "`" + ` u ON u.id = dt.user_id
WHERE u.role = 'patient' AND u.is_active = 1
`

func (q *Queries) ListActivePatientTokens(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActivePatientTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientTokensNeedingReminder = `-- name: ListPatientTokensNeedingReminder :many
SELECT dt.token
FROM device_token dt
JOIN ` + "`" + `user` + "`" + ` u ON u.id = dt.user_id
LEFT JOIN medication_log m ON m.user_id = u.id AND m.log_date = ?
WHERE u.role = 'patient' AND u.is_active = 1 AND m.id IS NULL
`

func (q *Queries) ListPatientTokensNeedingReminder(ctx context.Context, day time.Time) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPatientTokensNeedingReminder, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :execresult
INSERT INTO device_token (user_id, token, platform)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE user_id = VALUES(user_id), platform = VALUES(platform)
`

type UpsertDeviceTokenParams struct {
	UserID   int32  `json:"user_id"`
	Token    string `json:"token"`
	Platform string `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
}
