// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_token.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_token WHERE token = ?
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceToken, token)
	return err
}

const listActivePatientTokens = `-- name: ListActivePatientTokens :many
SELECT dt.token
FROM device_token dt
JOIN ` + "`" + `user` + "`" + ` u ON u.id = dt.user_id
WHERE u.role = 'patient' AND u.is_active = 1
`

func (q *Queries) ListActivePatientTokens(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActivePatientTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientTokensNeedingDailyLog = `-- name: ListPatientTokensNeedingDailyLog :many
SELECT DISTINCT dt.token
FROM device_token dt
JOIN ` + "`" + `user` + "`" + ` u ON u.id = dt.user_id
LEFT JOIN medication_log m ON m.user_id = u.id AND m.log_date = ?
LEFT JOIN activity_log a ON a.user_id = u.id AND a.log_date = ?
LEFT JOIN diet_log d ON d.user_id = u.id AND d.log_date = ?
LEFT JOIN glucose_log g ON g.user_id = u.id AND DATE(g.measured_at) = ?
WHERE u.role = 'patient' AND u.is_active = 1
  AND (m.id IS NULL OR a.id IS NULL OR d.id IS NULL OR g.id IS NULL)
`

type ListPatientTokensNeedingDailyLogParams struct {
	Day time.Time `json:"day"`
}

// Patients missing any of today's daily logs: medication, activity, diet, or glucose.
func (q *Queries) ListPatientTokensNeedingDailyLog(ctx context.Context, arg ListPatientTokensNeedingDailyLogParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPatientTokensNeedingDailyLog,
		arg.Day,
		arg.Day,
		arg.Day,
		arg.Day,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientTokensWithUnreadArticles = `-- name: ListPatientTokensWithUnreadArticles :many
SELECT DISTINCT dt.token
FROM device_token dt
JOIN ` + "`" + `user` + "`" + ` u ON u.id = dt.user_id
WHERE u.role = 'patient' AND u.is_active = 1
  AND EXISTS (
      SELECT 1 FROM education_article a
      WHERE a.is_published = 1
        AND NOT EXISTS (
            SELECT 1 FROM article_read ar
            WHERE ar.user_id = u.id AND ar.article_id = a.id
        )
  )
`

// Patients who have at least one published article they have not yet read.
func (q *Queries) ListPatientTokensWithUnreadArticles(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPatientTokensWithUnreadArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :execresult
INSERT INTO device_token (user_id, token, platform)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE user_id = VALUES(user_id), platform = VALUES(platform)
`

type UpsertDeviceTokenParams struct {
	UserID   int32  `json:"user_id"`
	Token    string `json:"token"`
	Platform string `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
}
