// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: education.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createArticle = `-- name: CreateArticle :execresult
INSERT INTO education_article (title, slug, category, cover_image_path, body_html, is_published, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateArticleParams struct {
	Title          string `json:"title"`
	Slug           string `json:"slug"`
	Category       string `json:"category"`
	CoverImagePath string `json:"cover_image_path"`
	BodyHtml       string `json:"body_html"`
	IsPublished    bool   `json:"is_published"`
	SortOrder      int32  `json:"sort_order"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createArticle,
		arg.Title,
		arg.Slug,
		arg.Category,
		arg.CoverImagePath,
		arg.BodyHtml,
		arg.IsPublished,
		arg.SortOrder,
	)
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM education_article WHERE id = ?
`

func (q *Queries) DeleteArticle(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, id)
	return err
}

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, title, slug, category, cover_image_path, body_html, is_published, sort_order, created_at, updated_at FROM education_article WHERE id = ? LIMIT 1
`

func (q *Queries) GetArticleByID(ctx context.Context, id int32) (EducationArticle, error) {
	row := q.db.QueryRowContext(ctx, getArticleByID, id)
	var i EducationArticle
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Category,
		&i.CoverImagePath,
		&i.BodyHtml,
		&i.IsPublished,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT id, title, slug, category, cover_image_path, body_html, is_published, sort_order, created_at, updated_at FROM education_article WHERE slug = ? AND is_published = 1 LIMIT 1
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (EducationArticle, error) {
	row := q.db.QueryRowContext(ctx, getArticleBySlug, slug)
	var i EducationArticle
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Category,
		&i.CoverImagePath,
		&i.BodyHtml,
		&i.IsPublished,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllArticles = `-- name: ListAllArticles :many
SELECT id, title, slug, category, cover_image_path, body_html, is_published, sort_order, created_at, updated_at FROM education_article ORDER BY sort_order ASC, id DESC
`

func (q *Queries) ListAllArticles(ctx context.Context) ([]EducationArticle, error) {
	rows, err := q.db.QueryContext(ctx, listAllArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EducationArticle
	for rows.Next() {
		var i EducationArticle
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Category,
			&i.CoverImagePath,
			&i.BodyHtml,
			&i.IsPublished,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
SELECT id, title, slug, category, cover_image_path, body_html, is_published, sort_order, created_at, updated_at FROM education_article WHERE is_published = 1 ORDER BY sort_order ASC, id DESC
`

func (q *Queries) ListPublishedArticles(ctx context.Context) ([]EducationArticle, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EducationArticle
	for rows.Next() {
		var i EducationArticle
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Category,
			&i.CoverImagePath,
			&i.BodyHtml,
			&i.IsPublished,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadArticleIDs = `-- name: ListReadArticleIDs :many
SELECT article_id FROM article_read WHERE user_id = ?
`

func (q *Queries) ListReadArticleIDs(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, listReadArticleIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var article_id int32
		if err := rows.Scan(&article_id); err != nil {
			return nil, err
		}
		items = append(items, article_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArticleRead = `-- name: MarkArticleRead :execresult
INSERT INTO article_read (user_id, article_id)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE read_at = NOW()
`

type MarkArticleReadParams struct {
	UserID    int32 `json:"user_id"`
	ArticleID int32 `json:"article_id"`
}

func (q *Queries) MarkArticleRead(ctx context.Context, arg MarkArticleReadParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markArticleRead, arg.UserID, arg.ArticleID)
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE education_article
SET title = ?, slug = ?, category = ?, cover_image_path = ?, body_html = ?, is_published = ?, sort_order = ?
WHERE id = ?
`

type UpdateArticleParams struct {
	Title          string `json:"title"`
	Slug           string `json:"slug"`
	Category       string `json:"category"`
	CoverImagePath string `json:"cover_image_path"`
	BodyHtml       string `json:"body_html"`
	IsPublished    bool   `json:"is_published"`
	SortOrder      int32  `json:"sort_order"`
	ID             int32  `json:"id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.ExecContext(ctx, updateArticle,
		arg.Title,
		arg.Slug,
		arg.Category,
		arg.CoverImagePath,
		arg.BodyHtml,
		arg.IsPublished,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
