// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countCompliantDays = `-- name: CountCompliantDays :one
SELECT COUNT(*) FROM (
    SELECT m.log_date
    FROM medication_log m
    JOIN activity_log a ON a.user_id = m.user_id AND a.log_date = m.log_date
    JOIN diet_log d ON d.user_id = m.user_id AND d.log_date = m.log_date
    WHERE m.user_id = ?
      AND m.log_date >= ?
      AND m.log_date <= ?
      AND m.taken_complete = 1 AND a.did_activity = 1 AND d.on_schedule = 1
) t
`

type CountCompliantDaysParams struct {
	UserID    int32     `json:"user_id"`
	LogDate   time.Time `json:"log_date"`
	LogDate_2 time.Time `json:"log_date_2"`
}

// Counts days in [from,to] where the patient completed all three daily pillars fully.
func (q *Queries) CountCompliantDays(ctx context.Context, arg CountCompliantDaysParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompliantDays, arg.UserID, arg.LogDate, arg.LogDate_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGlucoseLog = `-- name: CreateGlucoseLog :execresult
INSERT INTO glucose_log (user_id, measured_at, timing, value_mgdl)
VALUES (?, ?, ?, ?)
`

type CreateGlucoseLogParams struct {
	UserID     int32            `json:"user_id"`
	MeasuredAt time.Time        `json:"measured_at"`
	Timing     GlucoseLogTiming `json:"timing"`
	ValueMgdl  int32            `json:"value_mgdl"`
}

func (q *Queries) CreateGlucoseLog(ctx context.Context, arg CreateGlucoseLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGlucoseLog,
		arg.UserID,
		arg.MeasuredAt,
		arg.Timing,
		arg.ValueMgdl,
	)
}

const getActivityLog = `-- name: GetActivityLog :one
SELECT id, user_id, log_date, did_activity, per_doctor_advice, created_at, updated_at FROM activity_log WHERE user_id = ? AND log_date = ? LIMIT 1
`

type GetActivityLogParams struct {
	UserID  int32     `json:"user_id"`
	LogDate time.Time `json:"log_date"`
}

func (q *Queries) GetActivityLog(ctx context.Context, arg GetActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRowContext(ctx, getActivityLog, arg.UserID, arg.LogDate)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogDate,
		&i.DidActivity,
		&i.PerDoctorAdvice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDietLog = `-- name: GetDietLog :one
SELECT id, user_id, log_date, per_doctor_advice, on_schedule, created_at, updated_at FROM diet_log WHERE user_id = ? AND log_date = ? LIMIT 1
`

type GetDietLogParams struct {
	UserID  int32     `json:"user_id"`
	LogDate time.Time `json:"log_date"`
}

func (q *Queries) GetDietLog(ctx context.Context, arg GetDietLogParams) (DietLog, error) {
	row := q.db.QueryRowContext(ctx, getDietLog, arg.UserID, arg.LogDate)
	var i DietLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogDate,
		&i.PerDoctorAdvice,
		&i.OnSchedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMedicationLog = `-- name: GetMedicationLog :one
SELECT id, user_id, log_date, taken_complete, taken_on_time, created_at, updated_at FROM medication_log WHERE user_id = ? AND log_date = ? LIMIT 1
`

type GetMedicationLogParams struct {
	UserID  int32     `json:"user_id"`
	LogDate time.Time `json:"log_date"`
}

func (q *Queries) GetMedicationLog(ctx context.Context, arg GetMedicationLogParams) (MedicationLog, error) {
	row := q.db.QueryRowContext(ctx, getMedicationLog, arg.UserID, arg.LogDate)
	var i MedicationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogDate,
		&i.TakenComplete,
		&i.TakenOnTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT id, user_id, log_date, did_activity, per_doctor_advice, created_at, updated_at FROM activity_log
WHERE user_id = ? AND log_date BETWEEN ? AND ?
ORDER BY log_date DESC
`

type ListActivityLogsParams struct {
	UserID      int32     `json:"user_id"`
	FromLogDate time.Time `json:"from_log_date"`
	ToLogDate   time.Time `json:"to_log_date"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogs, arg.UserID, arg.FromLogDate, arg.ToLogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.DidActivity,
			&i.PerDoctorAdvice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDietLogs = `-- name: ListDietLogs :many
SELECT id, user_id, log_date, per_doctor_advice, on_schedule, created_at, updated_at FROM diet_log
WHERE user_id = ? AND log_date BETWEEN ? AND ?
ORDER BY log_date DESC
`

type ListDietLogsParams struct {
	UserID      int32     `json:"user_id"`
	FromLogDate time.Time `json:"from_log_date"`
	ToLogDate   time.Time `json:"to_log_date"`
}

func (q *Queries) ListDietLogs(ctx context.Context, arg ListDietLogsParams) ([]DietLog, error) {
	rows, err := q.db.QueryContext(ctx, listDietLogs, arg.UserID, arg.FromLogDate, arg.ToLogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DietLog
	for rows.Next() {
		var i DietLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.PerDoctorAdvice,
			&i.OnSchedule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlucoseLogs = `-- name: ListGlucoseLogs :many
SELECT id, user_id, measured_at, timing, value_mgdl, created_at FROM glucose_log
WHERE user_id = ? AND measured_at BETWEEN ? AND ?
ORDER BY measured_at DESC
`

type ListGlucoseLogsParams struct {
	UserID         int32     `json:"user_id"`
	FromMeasuredAt time.Time `json:"from_measured_at"`
	ToMeasuredAt   time.Time `json:"to_measured_at"`
}

func (q *Queries) ListGlucoseLogs(ctx context.Context, arg ListGlucoseLogsParams) ([]GlucoseLog, error) {
	rows, err := q.db.QueryContext(ctx, listGlucoseLogs, arg.UserID, arg.FromMeasuredAt, arg.ToMeasuredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlucoseLog
	for rows.Next() {
		var i GlucoseLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MeasuredAt,
			&i.Timing,
			&i.ValueMgdl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationLogs = `-- name: ListMedicationLogs :many
SELECT id, user_id, log_date, taken_complete, taken_on_time, created_at, updated_at FROM medication_log
WHERE user_id = ? AND log_date BETWEEN ? AND ?
ORDER BY log_date DESC
`

type ListMedicationLogsParams struct {
	UserID      int32     `json:"user_id"`
	FromLogDate time.Time `json:"from_log_date"`
	ToLogDate   time.Time `json:"to_log_date"`
}

func (q *Queries) ListMedicationLogs(ctx context.Context, arg ListMedicationLogsParams) ([]MedicationLog, error) {
	rows, err := q.db.QueryContext(ctx, listMedicationLogs, arg.UserID, arg.FromLogDate, arg.ToLogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedicationLog
	for rows.Next() {
		var i MedicationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.TakenComplete,
			&i.TakenOnTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActivityLog = `-- name: UpsertActivityLog :execresult
INSERT INTO activity_log (user_id, log_date, did_activity, per_doctor_advice)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE did_activity = VALUES(did_activity), per_doctor_advice = VALUES(per_doctor_advice)
`

type UpsertActivityLogParams struct {
	UserID          int32     `json:"user_id"`
	LogDate         time.Time `json:"log_date"`
	DidActivity     bool      `json:"did_activity"`
	PerDoctorAdvice bool      `json:"per_doctor_advice"`
}

func (q *Queries) UpsertActivityLog(ctx context.Context, arg UpsertActivityLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertActivityLog,
		arg.UserID,
		arg.LogDate,
		arg.DidActivity,
		arg.PerDoctorAdvice,
	)
}

const upsertDietLog = `-- name: UpsertDietLog :execresult
INSERT INTO diet_log (user_id, log_date, per_doctor_advice, on_schedule)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE per_doctor_advice = VALUES(per_doctor_advice), on_schedule = VALUES(on_schedule)
`

type UpsertDietLogParams struct {
	UserID          int32     `json:"user_id"`
	LogDate         time.Time `json:"log_date"`
	PerDoctorAdvice bool      `json:"per_doctor_advice"`
	OnSchedule      bool      `json:"on_schedule"`
}

func (q *Queries) UpsertDietLog(ctx context.Context, arg UpsertDietLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertDietLog,
		arg.UserID,
		arg.LogDate,
		arg.PerDoctorAdvice,
		arg.OnSchedule,
	)
}

const upsertMedicationLog = `-- name: UpsertMedicationLog :execresult
INSERT INTO medication_log (user_id, log_date, taken_complete, taken_on_time)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE taken_complete = VALUES(taken_complete), taken_on_time = VALUES(taken_on_time)
`

type UpsertMedicationLogParams struct {
	UserID        int32     `json:"user_id"`
	LogDate       time.Time `json:"log_date"`
	TakenComplete bool      `json:"taken_complete"`
	TakenOnTime   bool      `json:"taken_on_time"`
}

func (q *Queries) UpsertMedicationLog(ctx context.Context, arg UpsertMedicationLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertMedicationLog,
		arg.UserID,
		arg.LogDate,
		arg.TakenComplete,
		arg.TakenOnTime,
	)
}
