// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type GlucoseLogTiming string

const (
	GlucoseLogTimingBeforeMeal GlucoseLogTiming = "before_meal"
	GlucoseLogTimingAfterMeal  GlucoseLogTiming = "after_meal"
)

func (e *GlucoseLogTiming) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GlucoseLogTiming(s)
	case string:
		*e = GlucoseLogTiming(s)
	default:
		return fmt.Errorf("unsupported scan type for GlucoseLogTiming: %T", src)
	}
	return nil
}

type NullGlucoseLogTiming struct {
	GlucoseLogTiming GlucoseLogTiming `json:"glucose_log_timing"`
	Valid            bool             `json:"valid"` // Valid is true if GlucoseLogTiming is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGlucoseLogTiming) Scan(value interface{}) error {
	if value == nil {
		ns.GlucoseLogTiming, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GlucoseLogTiming.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGlucoseLogTiming) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GlucoseLogTiming), nil
}

type UserJenisKelamin string

const (
	UserJenisKelaminL UserJenisKelamin = "L"
	UserJenisKelaminP UserJenisKelamin = "P"
)

func (e *UserJenisKelamin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserJenisKelamin(s)
	case string:
		*e = UserJenisKelamin(s)
	default:
		return fmt.Errorf("unsupported scan type for UserJenisKelamin: %T", src)
	}
	return nil
}

type NullUserJenisKelamin struct {
	UserJenisKelamin UserJenisKelamin `json:"user_jenis_kelamin"`
	Valid            bool             `json:"valid"` // Valid is true if UserJenisKelamin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserJenisKelamin) Scan(value interface{}) error {
	if value == nil {
		ns.UserJenisKelamin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserJenisKelamin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserJenisKelamin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserJenisKelamin), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRolePatient UserRole = "patient"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStudyArm string

const (
	UserStudyArmIntervensi UserStudyArm = "intervensi"
	UserStudyArmKontrol    UserStudyArm = "kontrol"
)

func (e *UserStudyArm) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStudyArm(s)
	case string:
		*e = UserStudyArm(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStudyArm: %T", src)
	}
	return nil
}

type NullUserStudyArm struct {
	UserStudyArm UserStudyArm `json:"user_study_arm"`
	Valid        bool         `json:"valid"` // Valid is true if UserStudyArm is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStudyArm) Scan(value interface{}) error {
	if value == nil {
		ns.UserStudyArm, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStudyArm.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStudyArm) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStudyArm), nil
}

type ActivityLog struct {
	ID              int32     `json:"id"`
	UserID          int32     `json:"user_id"`
	LogDate         time.Time `json:"log_date"`
	DidActivity     bool      `json:"did_activity"`
	PerDoctorAdvice bool      `json:"per_doctor_advice"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type AuditTrail struct {
	ID        int32          `json:"id"`
	TableName string         `json:"table_name"`
	RowID     int32          `json:"row_id"`
	Action    string         `json:"action"`
	Changes   sql.NullString `json:"changes"`
	ActorID   sql.NullInt32  `json:"actor_id"`
	CreatedAt time.Time      `json:"created_at"`
}

type DietLog struct {
	ID              int32     `json:"id"`
	UserID          int32     `json:"user_id"`
	LogDate         time.Time `json:"log_date"`
	PerDoctorAdvice bool      `json:"per_doctor_advice"`
	OnSchedule      bool      `json:"on_schedule"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type EducationArticle struct {
	ID             int32     `json:"id"`
	Title          string    `json:"title"`
	Slug           string    `json:"slug"`
	Category       string    `json:"category"`
	CoverImagePath string    `json:"cover_image_path"`
	BodyHtml       string    `json:"body_html"`
	IsPublished    bool      `json:"is_published"`
	SortOrder      int32     `json:"sort_order"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type GlucoseLog struct {
	ID         int32            `json:"id"`
	UserID     int32            `json:"user_id"`
	MeasuredAt time.Time        `json:"measured_at"`
	Timing     GlucoseLogTiming `json:"timing"`
	ValueMgdl  int32            `json:"value_mgdl"`
	CreatedAt  time.Time        `json:"created_at"`
}

type MedicationLog struct {
	ID            int32     `json:"id"`
	UserID        int32     `json:"user_id"`
	LogDate       time.Time `json:"log_date"`
	TakenComplete bool      `json:"taken_complete"`
	TakenOnTime   bool      `json:"taken_on_time"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type PeerGroup struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID           int32            `json:"id"`
	Role         UserRole         `json:"role"`
	NamaLengkap  string           `json:"nama_lengkap"`
	Usia         int32            `json:"usia"`
	JenisKelamin UserJenisKelamin `json:"jenis_kelamin"`
	Pendidikan   string           `json:"pendidikan"`
	Pekerjaan    string           `json:"pekerjaan"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	GroupID      sql.NullInt32    `json:"group_id"`
	StudyArm     NullUserStudyArm `json:"study_arm"`
	IsActive     bool             `json:"is_active"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}
