// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peer_group.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPeerGroups = `-- name: CountPeerGroups :one
SELECT COUNT(*) FROM peer_group
`

func (q *Queries) CountPeerGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPeerGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPeerGroup = `-- name: CreatePeerGroup :execresult
INSERT INTO peer_group (name, description) VALUES (?, ?)
`

type CreatePeerGroupParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreatePeerGroup(ctx context.Context, arg CreatePeerGroupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPeerGroup, arg.Name, arg.Description)
}

const deletePeerGroup = `-- name: DeletePeerGroup :exec
DELETE FROM peer_group WHERE id = ?
`

func (q *Queries) DeletePeerGroup(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePeerGroup, id)
	return err
}

const getPeerGroup = `-- name: GetPeerGroup :one
SELECT id, name, description, created_at FROM peer_group WHERE id = ? LIMIT 1
`

func (q *Queries) GetPeerGroup(ctx context.Context, id int32) (PeerGroup, error) {
	row := q.db.QueryRowContext(ctx, getPeerGroup, id)
	var i PeerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPeerGroups = `-- name: ListPeerGroups :many
SELECT id, name, description, created_at FROM peer_group ORDER BY name ASC
`

func (q *Queries) ListPeerGroups(ctx context.Context) ([]PeerGroup, error) {
	rows, err := q.db.QueryContext(ctx, listPeerGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeerGroup
	for rows.Next() {
		var i PeerGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeerGroup = `-- name: UpdatePeerGroup :exec
UPDATE peer_group SET name = ?, description = ? WHERE id = ?
`

type UpdatePeerGroupParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	ID          int32  `json:"id"`
}

func (q *Queries) UpdatePeerGroup(ctx context.Context, arg UpdatePeerGroupParams) error {
	_, err := q.db.ExecContext(ctx, updatePeerGroup, arg.Name, arg.Description, arg.ID)
	return err
}
