// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AssignUserGroup(ctx context.Context, arg AssignUserGroupParams) error
	// Counts days in [from,to] where the patient completed all three daily pillars fully.
	CountCompliantDays(ctx context.Context, arg CountCompliantDaysParams) (int64, error)
	CountPatients(ctx context.Context, arg CountPatientsParams) (int64, error)
	CountPatientsActiveOn(ctx context.Context, arg CountPatientsActiveOnParams) (int64, error)
	CountPeerGroups(ctx context.Context) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (sql.Result, error)
	CreateAuditTrail(ctx context.Context, arg CreateAuditTrailParams) (sql.Result, error)
	CreateGlucoseLog(ctx context.Context, arg CreateGlucoseLogParams) (sql.Result, error)
	CreatePeerGroup(ctx context.Context, arg CreatePeerGroupParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteArticle(ctx context.Context, id int32) error
	DeletePeerGroup(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetActivityLog(ctx context.Context, arg GetActivityLogParams) (ActivityLog, error)
	GetArticleByID(ctx context.Context, id int32) (EducationArticle, error)
	GetArticleBySlug(ctx context.Context, slug string) (EducationArticle, error)
	GetAuditTrail(ctx context.Context, id int32) (AuditTrail, error)
	GetDietLog(ctx context.Context, arg GetDietLogParams) (DietLog, error)
	GetMedicationLog(ctx context.Context, arg GetMedicationLogParams) (MedicationLog, error)
	GetPeerGroup(ctx context.Context, id int32) (PeerGroup, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error)
	ListAllArticles(ctx context.Context) ([]EducationArticle, error)
	ListAuditTrails(ctx context.Context, arg ListAuditTrailsParams) ([]AuditTrail, error)
	ListDietLogs(ctx context.Context, arg ListDietLogsParams) ([]DietLog, error)
	ListGlucoseLogs(ctx context.Context, arg ListGlucoseLogsParams) ([]GlucoseLog, error)
	ListMedicationLogs(ctx context.Context, arg ListMedicationLogsParams) ([]MedicationLog, error)
	ListPatients(ctx context.Context, arg ListPatientsParams) ([]User, error)
	ListPatientsByGroup(ctx context.Context, groupID sql.NullInt32) ([]User, error)
	ListPeerGroups(ctx context.Context) ([]PeerGroup, error)
	ListPublishedArticles(ctx context.Context) ([]EducationArticle, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) error
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) error
	UpdatePeerGroup(ctx context.Context, arg UpdatePeerGroupParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertActivityLog(ctx context.Context, arg UpsertActivityLogParams) (sql.Result, error)
	UpsertDietLog(ctx context.Context, arg UpsertDietLogParams) (sql.Result, error)
	UpsertMedicationLog(ctx context.Context, arg UpsertMedicationLogParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
