// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_token.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :execresult
INSERT INTO password_reset_token (user_id, token_hash, expires_at)
VALUES (?, ?, ?)
`

type CreatePasswordResetTokenParams struct {
	UserID    int32     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
}

const getValidResetToken = `-- name: GetValidResetToken :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_token
WHERE token_hash = ? AND used_at IS NULL AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetValidResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getValidResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markResetTokenUsed = `-- name: MarkResetTokenUsed :exec
UPDATE password_reset_token SET used_at = NOW() WHERE id = ?
`

func (q *Queries) MarkResetTokenUsed(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, markResetTokenUsed, id)
	return err
}
