// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const assignUserGroup = `-- name: AssignUserGroup :exec
UPDATE ` + "`" + `user` + "`" + ` SET group_id = ?, study_arm = ? WHERE id = ?
`

type AssignUserGroupParams struct {
	GroupID  sql.NullInt32    `json:"group_id"`
	StudyArm NullUserStudyArm `json:"study_arm"`
	ID       int32            `json:"id"`
}

func (q *Queries) AssignUserGroup(ctx context.Context, arg AssignUserGroupParams) error {
	_, err := q.db.ExecContext(ctx, assignUserGroup, arg.GroupID, arg.StudyArm, arg.ID)
	return err
}

const countPatients = `-- name: CountPatients :one
SELECT COUNT(*) FROM ` + "`" + `user` + "`" + `
WHERE role = 'patient'
  AND (? = '' OR nama_lengkap LIKE CONCAT('%', ?, '%') OR username LIKE CONCAT('%', ?, '%'))
`

type CountPatientsParams struct {
	Search interface{} `json:"search"`
}

func (q *Queries) CountPatients(ctx context.Context, arg CountPatientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPatients, arg.Search, arg.Search, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPatientsActiveOn = `-- name: CountPatientsActiveOn :one
SELECT COUNT(DISTINCT u.id) FROM ` + "`" + `user` + "`" + ` u
LEFT JOIN medication_log m ON m.user_id = u.id AND m.log_date = ?
LEFT JOIN activity_log a ON a.user_id = u.id AND a.log_date = ?
LEFT JOIN diet_log d ON d.user_id = u.id AND d.log_date = ?
WHERE u.role = 'patient' AND (m.id IS NOT NULL OR a.id IS NOT NULL OR d.id IS NOT NULL)
`

type CountPatientsActiveOnParams struct {
	Day time.Time `json:"day"`
}

func (q *Queries) CountPatientsActiveOn(ctx context.Context, arg CountPatientsActiveOnParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPatientsActiveOn, arg.Day, arg.Day, arg.Day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO ` + "`" + `user` + "`" + ` (role, nama_lengkap, usia, jenis_kelamin, pendidikan, pekerjaan, username, password_hash, group_id, study_arm, email)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Role         UserRole         `json:"role"`
	NamaLengkap  string           `json:"nama_lengkap"`
	Usia         int32            `json:"usia"`
	JenisKelamin UserJenisKelamin `json:"jenis_kelamin"`
	Pendidikan   string           `json:"pendidikan"`
	Pekerjaan    string           `json:"pekerjaan"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	GroupID      sql.NullInt32    `json:"group_id"`
	StudyArm     NullUserStudyArm `json:"study_arm"`
	Email        sql.NullString   `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Role,
		arg.NamaLengkap,
		arg.Usia,
		arg.JenisKelamin,
		arg.Pendidikan,
		arg.Pekerjaan,
		arg.Username,
		arg.PasswordHash,
		arg.GroupID,
		arg.StudyArm,
		arg.Email,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM ` + "`" + `user` + "`" + ` WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, nama_lengkap, usia, jenis_kelamin, pendidikan, pekerjaan, username, password_hash, group_id, study_arm, is_active, created_at, updated_at, email FROM ` + "`" + `user` + "`" + ` WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.NamaLengkap,
		&i.Usia,
		&i.JenisKelamin,
		&i.Pendidikan,
		&i.Pekerjaan,
		&i.Username,
		&i.PasswordHash,
		&i.GroupID,
		&i.StudyArm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, nama_lengkap, usia, jenis_kelamin, pendidikan, pekerjaan, username, password_hash, group_id, study_arm, is_active, created_at, updated_at, email FROM ` + "`" + `user` + "`" + ` WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.NamaLengkap,
		&i.Usia,
		&i.JenisKelamin,
		&i.Pendidikan,
		&i.Pekerjaan,
		&i.Username,
		&i.PasswordHash,
		&i.GroupID,
		&i.StudyArm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, role, nama_lengkap, usia, jenis_kelamin, pendidikan, pekerjaan, username, password_hash, group_id, study_arm, is_active, created_at, updated_at, email FROM ` + "`" + `user` + "`" + ` WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.NamaLengkap,
		&i.Usia,
		&i.JenisKelamin,
		&i.Pendidikan,
		&i.Pekerjaan,
		&i.Username,
		&i.PasswordHash,
		&i.GroupID,
		&i.StudyArm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, role, nama_lengkap, usia, jenis_kelamin, pendidikan, pekerjaan, username, password_hash, group_id, study_arm, is_active, created_at, updated_at, email FROM ` + "`" + `user` + "`" + `
WHERE role = 'patient'
  AND (? = '' OR nama_lengkap LIKE CONCAT('%', ?, '%') OR username LIKE CONCAT('%', ?, '%'))
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListPatientsParams struct {
	Search interface{} `json:"search"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listPatients,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.NamaLengkap,
			&i.Usia,
			&i.JenisKelamin,
			&i.Pendidikan,
			&i.Pekerjaan,
			&i.Username,
			&i.PasswordHash,
			&i.GroupID,
			&i.StudyArm,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsByGroup = `-- name: ListPatientsByGroup :many
SELECT id, role, nama_lengkap, usia, jenis_kelamin, pendidikan, pekerjaan, username, password_hash, group_id, study_arm, is_active, created_at, updated_at, email FROM ` + "`" + `user` + "`" + ` WHERE role = 'patient' AND group_id = ? ORDER BY nama_lengkap ASC
`

func (q *Queries) ListPatientsByGroup(ctx context.Context, groupID sql.NullInt32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listPatientsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.NamaLengkap,
			&i.Usia,
			&i.JenisKelamin,
			&i.Pendidikan,
			&i.Pekerjaan,
			&i.Username,
			&i.PasswordHash,
			&i.GroupID,
			&i.StudyArm,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE ` + "`" + `user` + "`" + ` SET is_active = ? WHERE id = ?
`

type SetUserActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int32 `json:"id"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, setUserActive, arg.IsActive, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE ` + "`" + `user` + "`" + ` SET password_hash = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int32  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE ` + "`" + `user` + "`" + `
SET nama_lengkap = ?, usia = ?, jenis_kelamin = ?, pendidikan = ?, pekerjaan = ?, email = ?
WHERE id = ?
`

type UpdateUserProfileParams struct {
	NamaLengkap  string           `json:"nama_lengkap"`
	Usia         int32            `json:"usia"`
	JenisKelamin UserJenisKelamin `json:"jenis_kelamin"`
	Pendidikan   string           `json:"pendidikan"`
	Pekerjaan    string           `json:"pekerjaan"`
	Email        sql.NullString   `json:"email"`
	ID           int32            `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.NamaLengkap,
		arg.Usia,
		arg.JenisKelamin,
		arg.Pendidikan,
		arg.Pekerjaan,
		arg.Email,
		arg.ID,
	)
	return err
}
